server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/praween-imalsha/spms_config
          default-label: main
          username: praween-imalsha


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      # url set api_gatway
